//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKhoHang
    {
        public int Id { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> IdKh { get; set; }
        public Nullable<int> ConLai { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
    
        public virtual KhoHang KhoHang { get; set; }
    }
}
