//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.SuDungDichVus = new HashSet<SuDungDichVu>();
        }
    
        public int Id { get; set; }
        public Nullable<System.TimeSpan> TimeStar { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> IdKH { get; set; }
        public Nullable<int> IdDate { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> IdGG { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string MaGG { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string MaDat { get; set; }
        public string TenPhong { get; set; }
        public Nullable<double> TienGiamGia { get; set; }
        public Nullable<double> TienDichVu { get; set; }
        public Nullable<double> Tienlich { get; set; }
        public string LoaiP { get; set; }
        public Nullable<bool> TrangThaiNhan { get; set; }
        public Nullable<int> IdTime { get; set; }
        public Nullable<int> IdLoai { get; set; }
        public Nullable<int> IdPhong { get; set; }
        public Nullable<int> IdLich { get; set; }
    
        public virtual DaysOfWeek DaysOfWeek { get; set; }
        public virtual GiammGia GiammGia { get; set; }
        public virtual KhachHangg KhachHangg { get; set; }
        public virtual LichDatP LichDatP { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual Time Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuDungDichVu> SuDungDichVus { get; set; }
    }
}
