//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int IDHoaDon { get; set; }
        public int IDDatPhong { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBatDau { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKetThuc { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> TienDv { get; set; }
        public Nullable<double> TienGG { get; set; }
        public Nullable<double> TienPhong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Tenkh { get; set; }
        public string TenP { get; set; }
        public Nullable<double> TienThem { get; set; }
        public Nullable<double> TienGiam { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> IdSDDV { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual SuDungDichVu SuDungDichVu { get; set; }
    }
}
