//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoHang()
        {
            this.CTKhoHangs = new HashSet<CTKhoHang>();
            this.DichVu1 = new HashSet<DichVu1>();
        }
    
        public int IDMatHang { get; set; }
        public string TenMatHang { get; set; }
        public double DonGia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> LoaiDv { get; set; }
        public Nullable<int> IDDonVT { get; set; }
        public int ConLai { get; set; }
        public Nullable<double> TongGia { get; set; }
        public Nullable<int> Soluongthem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTKhoHang> CTKhoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu1> DichVu1 { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual LoaiDV LoaiDV1 { get; set; }
    }
}
