//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int Id { get; set; }
        public string TenKH { get; set; }
        public string NoiDung { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public int TrangThai { get; set; }
        public System.DateTime NgayLH { get; set; }
    }
}
