//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DatPhongs = new HashSet<DatPhong>();
            this.LichDatPs = new HashSet<LichDatP>();
        }
    
        public int IDPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<int> SoLuongNguoi { get; set; }
        public int IDLoaiPhong { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichDatP> LichDatPs { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
