//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuDungDichVu()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<int> IDDv { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public string TenDVT { get; set; }
        public string TenLoai { get; set; }
        public Nullable<int> Idkh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBatDat { get; set; }
        public Nullable<int> IdDP { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual DichVu1 DichVu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KhachHangg KhachHangg { get; set; }
    }
}
