//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKaraoke.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin
    {
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string Hinhanh { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string ThongTinn { get; set; }
    }
}
